### ISSUE TITLE
Implementation of Stepper and some rewrite

### ISSUE THREAD

**Issue by wlwatkins** [fpagliughi/phidget-rs#1]
Hi, 

I'm about to use some phidgets modules for a project. I found your wrapper and i hope it will save me a lot of time. 
So first of all well done and thanks. 

I actually need the stepper motor implementation so I added it however, I've made many small changes to better fit my programming style. 
Nevertheless, I wanted to tell you about it. I still haven't tested the code on hardware as it is still in the mail. 
Hopefully, I'll have it validated within 1 month or so. 

I've forked the project and made my changes. If these changes interest you, I can make a merge request. 

However as I said I have modified quite a bit and these will be breaking changes. Anyway, let me know 

https://github.com/willmendil/phidget-rs

Best regards

w

**Comment by fpagliughi** [comment]
Hey @wlwatkins. Thanks for leaving the note. As a weird coincidence, I noticed the fork and had a quick look at your code earlier this week. (Probably because it's the only external activity on this library so far!)

The quality of your code looks great, so definitely no issues there. As the brief README states, this library is meant for a production environment, but our project was delayed (moving from an old C++ library to this one in Rust), so _some_ breaking changes would be fine, but I do see a few problems that would prevent me from being able to merge your code so that we can still use it.

Our target is Embedded Linux, specifically using Yocto. We're currently on the "Langdale" version, which (very) unfortunately leaves us tied to Rust v1.63 at the moment. Even the lastest Yocto is only up to v1.68.1. 

So that means we can update the MSRV a few versions, but not past 1.63, and perhaps some of the dependency versions need to stay put as well, so as not to cause problems with the older compiler.

We also use the examples and utility app to test our different setups. Those have lots of different hardware configurations, so the use of command-line arguments is essential, and thus we need the `clap` options. IIRC, I went through the trouble so that inclusion of the binaries is optional, and you don't pull in the `clap` dependency unless you request the examples or `utils` feature. So the base, default, library build wouldn't bring it in.

And the format file is just a nit. We standardize on formatting, but in this crate, it amounts to the difference in three lines of code. I'd prefer to keep it, but don't think it's a big deal either way.

Everything else looks fine. I do want to keep adding hardware module support to this, even for stuff we don't use. The stepper motor stuff looks cool, though I don't have the hardware to test it. I'm fine with splitting out the separate input and output modules for digital and analog.

So let me know what you think. It would be cool to keep a single library and not have to maintain separate forks.

**Comment by wlwatkins** [comment]
Great to hear! And thanks for the complements. I understand the `optional = true` now, had never seen this before. (had never seen many tricks you've implemented TBH). 

I'll thus see if I can modify my contribution to make it compatible with your implementation. But for this, I have a few questions:

- Do you confirm that the version of rust set in `Cargo.toml`, does not prevent the use of the crate in a newer version ?  I tested it and seems to work, but I'm not certain. 
- Regarding the testing, would it be acceptable to make a specific bin for your testing that would use this _vanilla_ crate? I believe this would make it more universal, wouldn't it? The same reasoning could be had with `bin/phidget.rs`.
- Regarding `.rustfmt.toml` your comment says it requires nightly, so if I understand correctly, this means one needs rust-nightly which would limit use in none nightly project. Do I understand this correctly?
- What version of phidgets do you use? Because I did the tests in debug, but when running `cargo build --release`, it seems to break? I personally have `Phidget22 - Version 1.18 - Built Jan 23 2024 13:44:35`

```
  = note: libphidget-f48eaf86022cdb5b.rlib(phidget-f48eaf86022cdb5b.phidget.6fa42f15874a8a6b-cgu.1.rcgu.o) : error LNK2019: unresolved external symbol PhidgetNet_removeAllServers referenced in function _ZN7phidget3net18remove_all_servers17h787270a32b575f26E   
```

I reran bindgen. It had me replace nearly every `u32` and `c_uint` with their signed equivalents
you can see this here https://github.com/wlwatkins/phidget-rs/tree/new-bindgen  (yes I've changed my username since this morning)

edit: OK so it seems the linking error is an issue with 

```rust
/// Removes all registered servers.
pub fn remove_all_servers() -> Result<()> {
    ReturnCode::result(unsafe { ffi::PhidgetNet_removeAllServers() })
}
```

Removing it works. 

```rust
/// Removes all registered servers.
pub fn remove_all_servers() -> Result<()> {
    unimplemented!();
    // The code below breaks linkage. Looking at the functions available for [C Networking](https://www.phidgets.com/?view=api), removeAllServers is not listened.
    // ReturnCode::result(unsafe { ffi::PhidgetNet_removeAllServers() })
}
```

Tell me if the new bindgen is a problem for you, I'll then make a PR on your repo and we can then make some changes in a new branch, and once everything looks good, we can make the release.

I'll have quite some time on my hands for the next few weeks, so I'll try to mechanically add other devices.

**Comment by fpagliughi** [comment]
> Do you confirm that the version of rust set in Cargo.toml, does not prevent the use of the crate in a newer version ? I tested it and seems to work, but I'm not certain.

Yes, can confirm. Rust is wonderfully backward compatible. You can do all your development with the latest compiler; the only thing you need to worry about is using a function that was introduced after the MSRV, or updating a dependency that is too new.

> Regarding the testing, would it be acceptable to make a specific bin for your testing that would use this vanilla crate? I believe this would make it more universal, wouldn't it? The same reasoning could be had with bin/phidget.rs.

I've seen it done both ways. Some people like to make a workspace in one repository with separate crates for the library, CLI, and examples. But that requires you to maintain separate crates, and publish all them independently to crates.io.

I much prefer to keep everything together and let you build what you need via Cargo features. The vast majority of users will just pull the library into their project via a Cargo dependency, and just get the sub-dependencies they need (i.e. no clap).

> Regarding .rustfmt.toml your comment says it requires nightly, so if I understand correctly, this means one needs rust-nightly which would limit use in none nightly project. Do I understand this correctly?

You just need nightly to run the formatter... not to build the code. So user's definitely don't need nightly. Developers and contributors, like yourself, can use to to run the formatter if you desire, but honestly, I wouldn't reject a PR simply because it failed the formatter check! I'd reformat it later.
 
> What version of phidgets do you use? Because I did the tests in debug, but when running cargo build --release, it seems to break? I personally have Phidget22 - Version 1.18 - Built Jan 23 2024 13:44:35

I used the most recent version the last time I was working on it!  Last summer(?)
We can and should keep it current with the latest Phidgets library at the time of a release. And I should definitely document that better if they are releasing updates with the same version number that contains breaking changes!!!

I'll have a look at their latest version to see what's changed ASAP - maybe tomorrow. (I'm in Eastern USA)

**Comment by fpagliughi** [comment]
I just had a look. It appears that I have the latest C library on my machine (v1.18.20240123). I installed _phidet22_ on Mint/Ubuntu Linux with the package manager, so have been updating despite not building the Rust library in a few months.

The crate builds fine on Linux with the latest library. What platform are you using?

**Comment by wlwatkins** [comment]
I'm on windows, 

This is how i did the binding : https://github.com/wlwatkins/phidget-rs/blob/new-bindgen/phidget-sys/README.md

```toml
[build-dependencies]
bindgen = "0.69.4"
```

maybe it's a question of settings?

**Comment by fpagliughi** [comment]
I don't see any conditional compilation in _phidgets22.h_ from the Linux version, other than some linkage/ABI stuff at the top. But that little bit would lead me to believe it's the same header for both platforms.

I don't use Windows for anything, but I keep a machine around to test some open-source code. I can try this out in the next day or two.

As for bindgen, I went crazy with my first Rust library years ago...
https://github.com/eclipse/paho.mqtt.rust/tree/master/paho-mqtt-sys

I pre-generated bindings for every platform I had available (Windows, Mac, Linux for x86-64, ARM 32 & 64) and also made a  Cargo build feature to generate bindings during the build, just in case. But mostly I found that you just need to be careful to have separate bindings for 32-bit systems and 64-bit systems, to make sure that pointers are aligned. If you mix them up you get segfaults.

We can figure out if we need to do anything like that here, beyond some 32-bit bindings, but I hope it doesn't get complicated.

**Comment by wlwatkins** [comment]
To-do list

- [ ] Verify if bindings generate by @fpagliughi is sufficient as is or if the newly generated bindgen from @wlwatkins is the updated version of phidget33.h
- [ ] Reimplement the clap examples required by @fpagliughi in the new code in order to prepare the PR
- [ ] Finalise the building features for x32 and x64.
- [ ] Propose a PR to merge in @fpagliughi unofficial repo.
- [ ] later on: ... add new hardware and start working on the documentation (README.md, more generic examples, etc...)


what do you think?

**Comment by fpagliughi** [comment]
Sounds good.

I can do the 32 and 64-bit bindings and get `build.rs` fixed up for it. I'm set up to do that.

For the rest of it, don't feel like you need to do it all at once. In fact, that makes it harder to test everything and/or accept/reject individual parts. For example, from the stuff you've done, maybe send over a PR that pulls out the input and output analog & GPIO into separate modules. Then a PR to add the stepper motor code. etc.

Does that make sense?

**Comment by fpagliughi** [comment]
Yes, I don't see any contact info for him, but can you try to contact him and ask to submit a PR?If not, I prefer to get consent to grab the code and merge it, even if the license would allow us to grab it.

And we should ask and/or try to determine if the code it working. (I don't have any Phidget motor controllers to test it).

**Comment by wlwatkins** [comment]
He has very little activity on his profil, so I you had no reponse, it's not very hopefull. Do you want to enable the discussion tab in github, so we can talk without "poluting" the issue section? just an idea. 
and regarding the testing, I absolutly agree, hence why getting the attention of phidget them selves could be of interest.

**Comment by wlwatkins** [comment]
Hi, I got some good news, I received the kit and thus can confirm that the stepper code works. I need to change the example as it needs a few more lines. 
I guess, the next step is to update the crate.io and fill in the README, I'll do a PR for the readme when i have time, and once we get something working, i'll get in touch with phidget to see how we can continue adding the rest of the hardware.

**Comment by fpagliughi** [comment]
Cool. When you think the stepper code is finished and validated, let me know and I will move to release it.

Also, I announced this project on their forum last year, but got not a single reply or mention about it anywhere.
https://www.phidgets.com/phorum/viewtopic.php?t=10654

But feel free to contact them and see if they would help to support it in any way.

**Comment by wlwatkins** [comment]
I had them on the phone, and they said they had no resources to add more languages, which is a pity, especially since we might be talking about a community driven repo. anyway


i realised that some of the comments in https://github.com/fpagliughi/phidget-rs/blob/master/src/phidget.rs are oriented towards your specific use case. I'll try to go through them when i have time

**Comment by fpagliughi** [comment]
Oh, yeah. Looks like some copy-paste errors from when I split out the base Phidget implementation. I can get that cleaned up.

**Comment by fpagliughi** [comment]
I think we're all good with this? I will close, but feel free to re-open if there's anything else. Or open a new ticet.
